name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies
        run: dotnet restore UserAuthAPI.sln
      - name: Build
        run: dotnet build UserAuthAPI.sln --configuration Debug
      - name: List directory contents
        run: ls -R ./bin/Debug/net8.0
      - name: Build Docker image
        run: |
          docker build -t wagnersimonetto/userauthapi:v1 .
      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_HUB_PASSWORD }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push wagnersimonetto/userauthapi:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: |
            {
            "clientId": "c448f917-8bae-4cda-b3d7-c5e67abac89e",
            "clientSecret": "zC18Q~REhEpxy2VHhAgyJygBgK.6x1XHDUa9KbD.",
            "subscriptionId": "563c6d07-c899-49cd-bd5f-6c2e07914e35",
            "tenantId": "11dbbfe2-89b8-4549-be10-cec364e59551"
            }

      - name: Deploy to Azure
        run: |
          az webapp config container set --name atividadebdd --resource-group FIAP --container-image-name wagnersimonetto/userauthapi:v1
